version: '3'

services:
  category-service:
    image: khusan/ms1:1.0.0
    build:
      context: .
      args:
        version: ${API_VERSION}
    volumes:
      - ./build/libs/ms1-${API_VERSION}.jar:/opt/demo/lib/category-ms.jar
    ports:
      - "7070:7070"
      - "8081:8081"
    restart: "no"
    environment:
      - OPEN_CAGE_API_KEY=6bd842a1b5af4b40af060e7e2f7fe94c