version: '3'

services:

  mongodb:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    restart: "always"


  category-service:
    image: khusan/ms1:1.0.1
    build:
      context: .
      args:
        version: ${API_VERSION}
    volumes:
      - ./build/libs/ms1-${API_VERSION}.jar:/opt/demo/lib/category-ms.jar
    ports:
      - "7070:7070"
      - "8081:8081"
    restart: "no"
    environment:
      - MONGODB_HOST=mongo
      - MONGODB_PORT=27017
      - OPEN_CAGE_API_KEY=6bd842a1b5af4b40af060e7e2f7fe94c