server:
  port: 7070


info:
  app:
    name: ${spring.application.name}
    version: "@application.version@"
    description: "@application.description@"
spring:
  application:
    name: OpenCage integration
  data:
    mongodb:
      host: ${MONGO_DB_HOST:localhost}
      port: ${MONGO_DB_PORT:27017}

external:
  services:
    opencage:
      api_key: ${OPENCAGE_API_KEY:6bd842a1b5af4b40af060e7e2f7fe94c}